---
abstract: 'A phone friendly web interface for RT'
author:
  - 'Jesse Vincent <jesse@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-MobileUI
no_index:
  directory:
    - html
    - inc
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.9
